---
title: "Garder rapport SpecCondStat"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

## Chargement des paquets

```{r Library, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
library("readxl") 
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis) # couleur daltonien
library(tidyr) # fonction gather
library(qcc)
library(gplots)
library(RColorBrewer)
library(vegan) # Un premier lot de fonctions pour ordination
library(FactoMineR) # Deux autres packages faisant la m?me chose mais en plus esth?tique
library(factoextra)
library(ape) #PCoA
library(ade4)
library(grid) # Annotation sur le graphique

```

## Importation des données
```{r Import, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

# Import
SCS <- read_excel("SpecCondStat.xls")
```


```{r Nettoyage}
# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Bombus (Bombus)  sp."
SCS$sp[SCS$sp == "Terrestribombus  sp."] <- "Bombus (Bombus)  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
```


```{r}
# Sélection des colonnes
bee_sp <- select(SCS, N, sp)
# Addition des sp pour l'ensemble des sites
bee_sp <- aggregate(N ~ sp, data = bee_sp, sum)
# Ordonne les sp par ordre décroissant d'abondance
bee_sp <- bee_sp[order(bee_sp $N, decreasing = TRUE),]
# Encode la colonne sp en facteur
bee_sp$sp <- factor(bee_sp$sp, levels = bee_sp$sp)
# Accumulation de l'abondance
bee_sp$cumulative <- cumsum(bee_sp$N)
```


```{r rang d'abondance ggplot }
# Nombre de singleton et doubleton
length(which(bee_sp$N == 1))
length(which(bee_sp$N == 2))

# Début enregistrement .pdf
pdf(file = "D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Rapport de mémoire/figure/pareto_chart_ggplot.pdf",   # The directory you want to save the file in
    width = 20, # The width of the plot in inches
    height = 10)

# Pourcentage cumulative
bee_sp$cumulative <- 100 * bee_sp$cumulative/tail(bee_sp$cumulative, n=1)
scaleRight <- tail(bee_sp$cumulative, n=1)/head(bee_sp$N, n=1)

ggplot(bee_sp, aes(x = sp)) +
  geom_bar(aes(y = N), fill = "dark red",  stat="identity", color="black") +
  labs(title = "Espèce par rang d'abondance", x = 'Espèces', y = 'Abondance') +
  #scale_y_continuous(sec.axis = sec_axis(~.*scaleRight, name = "Cumulative (%)")) +
  geom_point(aes(y = cumulative/scaleRight), color = "black", pch=16, size=1) +
  scale_y_continuous(sec.axis = sec_axis(~.*scaleRight, name = "Pourcentage cumulative (%)", breaks = seq(0, 100, 10))) + # 2ème axe-y : grille
  #geom_path(aes(y=cumulative, group=1), colour="slateblue1", lty=3, size=0.9) +
  geom_vline(xintercept = "Andrena humilis", colour = "dark red", size=1.1) + # ligne vertical doubleton
  annotation_custom(grobTree(textGrob("Doubleton", x=0.74,  y=0.8, hjust=0, gp=gpar(col="dark red", fontsize=15)))) + # texte doubleton
  geom_vline(xintercept = "Andrena nigroaenea", colour = "dark red", size=1.1) + # ligne vertical singleton
  annotation_custom(grobTree(textGrob("Singleton", x=0.863,  y=0.8, hjust=0, gp=gpar(col="dark red", fontsize=15)))) + # texte singleton
  theme(axis.title.x = element_text(face="bold", size = 10), # Titre axe x
        axis.title.y = element_text(face="bold", size = 10), # Titre axe y
        axis.title.y.right = element_text(angle = 90), # Angle 2ème axe y
        axis.text.x = element_text(face="bold", color= "black", size=10, angle=90, hjust=0), # Echelle x
        axis.text.y = element_text(face="bold", color= "black", size=10), # Echelle y
        panel.background = element_rect(fill='white', colour='black'),
        panel.grid.major.y = element_line(colour = "gray70", size = 0.5, linetype = "dashed"),
        panel.grid.minor.y = element_line(colour = "gainsboro", size = 0.1, linetype = "dashed")) 

# Fin enregistrement .pdf
dev.off()

# Enregistrement avec ggsave()
# ggsave(filename = "pareto_chart.pdf", device = cairo_pdf)
# ggsave(filename = "pareto_chart.png")

```




```{r pareto.chart qcc}
# Ne sera pas utilisé finalement

# Nombre de singleton et doubleton
length(which(bee_sp$N == 1))
length(which(bee_sp$N == 2))
#pdf(file = "D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Rapport de mémoire/figure/pareto_chart.pdf",   # The directory you want to save the file in
 #   width = 20, # The width of the plot in inches
  #  height = 10)

# Rajouter avec ppt les singletons et doubletons (doublet/couple)
qcc.options(bg.margin="white")
pareto.bee_sp <- bee_sp$N
names(pareto.bee_sp) <- bee_sp$sp
pareto.chart(pareto.bee_sp, cumperc = seq(0, 100, by = 10), 
             ylab = "Abondance", ylab2 = "Pourcentage cumulative",
             main = "Espèce par rang d'abondance",
             col = "dark red", border = "green",add.stats=TRUE) 

#dev.off()

# ggsave ne fonctionne par avec cette fonction
# ggsave(filename = "pareto_chart.pdf", device = cairo_pdf)
# ggsave(filename = "pareto_chart.png")
```



