---
title: "beta"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(ggplot2)
library(vegan)
library(dplyr)
library(readxl)
library(iNEXT)
library("pheatmap")
```

Importation des données.
```{r Import}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

SpecCondStat <- read_excel("SpecCondStat.xls")


# Nom plus compact
SCS <- SpecCondStat

## Nettoyage
# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "Site" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "Apis mellifera"
SCS <- filter(SCS, sp != "Apis mellifera" )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus (Bombus)  sp."] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$Site[SCS$Site == "Les Gourmandes de la Procession"] <- "Gourmandes"


#### Abbréger le nom des sites
# Liste des Potagers
Potagers <- c("Abbaye St-Denis", "Rue de l'Egalite", "Chasse Cambier", "Mel Legumes", "Gourmandes", "Jean d'Avesnes", "Parc du bois de Mons", "Jardin Suspendu", "Ecole de l'Esperance", "Fond du petit marais")
# Liste des Parcs
Parcs <- c("Village des abeilles", "Siege social", "Parc du Beffroi", "Stievenart", "Parc Bonaert")

SCS$Code <- fct_collapse(
    SCS$Site,
    "Potager" = Potagers,
    "Parc" = Parcs)

# substring prend les premiers caractères, abbreviate abrège comme il le sent
SCS$code_site <- paste(substring(SCS$Code, 0,3),"-", SCS$Site)
# retirer les apostrophes
SCS$code_site <- gsub(" ", "", SCS$code_site)
```

```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, code_site)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + code_site, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ code_site + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)
```
# Matrice non-raréfié
## Abondance
```{r}
# Matrice dissimilarité d'abondance
dis <- vegdist(sqrt (data_bee_sp), method = 'bray', diag =TRUE)
D_chisq_R <- as.matrix(dis)
pheatmap(D_chisq_R, display_numbers = round(D_chisq_R, 2))
# exporter en 8x8
```
## Occurence
```{r}
# Matrice dissimilarité d'occurence
occurence <- as.data.frame(data_bee_sp) %>%
  transmute_all(~if_else(. > 0, 1, 0))
occurence_r <- (occurence)
D_jacc_R <- as.matrix(vegdist(occurence_r, method = "jaccard"))
pheatmap(D_jacc_R, display_numbers = round(D_jacc_R, 2))
```
# Matrice raréfié
Raréfaction à 39 individus + racine carré
```{r}
# Raréfaction à 39 individus (Parc Bonaert a le plus petit nbr d'individus)
bee.rare39 <- rarefy(data_bee_sp, sample = 39)
dis <- vegdist(bee.rare39, method = 'bray') # percentage cover data are transformed by square root
```
## Abondance
```{r}
# Matrice dissimilarité d'abondance
#dis <- vegdist(sqrt (bee.rare39), method = 'bray', diag =TRUE)
D_chisq_R <- as.matrix(dis)
pheatmap(D_chisq_R, display_numbers = round(D_chisq_R, 2))
# exporter en 8x8
```
Ca n'a pas de sens de raréfié des données de présence absence
```{r}
# Matrice dissimilarité d'occurence
# 
```




