---
title: "cca"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
# Load the required packages
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(forcats )
library(reshape2)
library("readxl") 
```

Importation des données.
```{r}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

# Import
granulo <- read_excel("granulo.xlsx")
granulo_simple <- read_excel("granulo.xlsx", sheet = "simple")
SpecCondStat <- read_excel("SpecCondStat.xls")
```

```{r Nettoyage}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes"
granulo$Site[granulo$Site == "Les Gourmandes de la Procession"] <- "Gourmandes"

row.names(granulo) <- granulo$Site
granulo <- select(granulo, -Site, -Texture)

row.names(granulo_simple) <- granulo_simple$Site
granulo_simple <- select(granulo_simple, -Site)
```


```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + sites, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ sites + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)
```

Pas de sable fin, vif = 36535.545
```{r}
# https://blogs.ncl.ac.uk/mep/2018/04/08/reproducible-publication-quality-multivariate-plots-in-r/
library(ggrepel)

varechem <- as.data.frame(granulo[c("Argile", "Limon fin", "Limon grossier", "Sable grossier")])
varespec <- as.data.frame(data_bee_sp)
vare_cca <- vegan::cca(varespec ~ ., varechem)


vare_spp_sco <- scores(vare_cca, display = "species")
vare_sam_sco <- scores(vare_cca, display = "sites")
vare_env_sco <- scores(vare_cca, display = "bp")
vare_spp_tbl <- as_tibble(vare_spp_sco)
vare_sam_tbl <- as_tibble(vare_sam_sco)
vare_env_tbl <- as_tibble(vare_env_sco)
vare_spp_tbl <- mutate(vare_spp_tbl, vgntxt=rownames(vare_spp_sco),
                       ccatype = "species")
vare_sam_tbl <- mutate(vare_sam_tbl, vgntxt=rownames(vare_sam_sco),
                       ccatype = "sites")
vare_env_tbl <- mutate(vare_env_tbl, vgntxt=rownames(vare_env_sco),
                       ccatype = "bp")

ggplot(vare_spp_tbl, aes(x = CCA1, y = CCA2, label = vgntxt)) +
       geom_point() +
       geom_text_repel(seed = 123)



rescaled <- vare_env_tbl %>% 
            select(CCA1, CCA2) %>%
            as.matrix() * 1.5
vare_tbl <- select(vare_env_tbl, vgntxt, ccatype) %>%
            bind_cols(as_tibble(rescaled)) %>%
            bind_rows(vare_spp_tbl)

ggplot() +
  geom_point(aes(x=CCA1, y=CCA2), data=filter(vare_tbl, ccatype=="species"))  +
  geom_text_repel(aes(x=CCA1, y=CCA2, label=vgntxt, size=3.5),
                  data=vare_tbl, seed=123) + 
  geom_segment(aes(x=0, y=0, xend=CCA1, yend=CCA2), arrow=arrow(length = unit(0.2,"cm")),
               data=filter(vare_tbl, ccatype=="bp"), color="blue") +
  coord_fixed() +
  theme_bw() +
  theme(legend.position="none")

summary(vare_cca)
RsquareAdj(vare_cca)
```
```{r}
vif.cca(vare_cca)
```

Test anova sur toutes les variables simplifiés
```{r}
# test l'ensemble de la CCA si le modèle explique une quantité significatif de la variation dans les données
anova(vare_cca) 
# test pour chacune des var env
anova(vare_cca, by = "term", permutations = 999)
# # test pour la significativité des effets marginaux (jsp c'est quoi)
# anova(vare_cca, by = "mar", permutations = 999)
# # test pour la significativité de chaque axe (jsp pq)
# anova(vare_cca, by = "axis", permutations = 999)
```
```{r}
permutest(vare_cca, permutations = 999)
permutest(vare_cca, by = "term", permutations = 999)
```



Soit je fais `Argile`, `Limon fin`, `Limon grossier`,  `Sable grossier`
Et J'ai un meilleur R², mais je n'aime pas trop le graphique
Soit je fais `Argile` `Limon fin` `Sable fin`
Et j'ai un graphique plus facile à lire
