---
title: "cca nidification sol"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

## Chargement des paquets
```{r Library, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
library("readxl") 
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis) # couleur daltonien
library(tidyr) # fonction gather
library("writexl")
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(forcats)
```

## Importation des données
```{r Import, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2/Traits abeilles")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2/Traits abeilles")

# Import
traits <- read_excel("Trait-bee-each-site.xlsx")
SpecCondStat <- read_excel("SpecCondStat.xls")
soil <- read_excel("Soil_R.xlsx")
```
Jeux de données SCS
```{r}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
soil$Site[soil$Site == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
```
Matrice metal X site
```{r}
### Sol
## Metaux
# Créer une colonne Code en fonction des types de sites
soil$Code <- fct_collapse(
    soil$Site,
    "Potager" = Potagers,
    "Parc" = Parcs)

# Garder pour rownames
soil_site_name <- select(soil, Site)

# Garder les métaux seulement
metal <- soil[, c("As", "Cd", "Cr", "Cu", "Hg", "Pb", "Ni", "Zn")]
row.names(metal) <- soil_site_name$Site
```
Lister les espèces terricoles
```{r}
# Addition des genres avec la zone de nidification (au dessus du sol ou en dessous)
nest_substrat <- aggregate(N ~ sp + Nest_area, data = traits, sum)

# Filtrer les espèces terricoles
soil_sp <- filter(nest_substrat, Nest_area == "Soil")
```
Matrice espèces terricoles X sites
```{r}
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
# Filtrer les sp terricoles
data_bee_soil <- filter(data_bee_sp, sp %in% soil_sp$sp)
data_bee_soil <- aggregate(N ~ sp + sites, data = data_bee_soil, sum)
data_bee_soil <- xtabs(N ~ sites + sp, data_bee_soil)
data_bee_soil <- type.convert(data_bee_soil)
```

```{r}
spe <- data_bee_soil
# le "." signifie contre toutes les var env; 1 : signifie aucune var env
spe.cca <- cca(spe ~ ., metal)
summary(spe.cca) # Scaling 2 (default)
# Unadjusted and adjusted R^2 - like statistics
RsquareAdj(spe.cca)
```

```{r}

```


```{r}
par(mfrow = c(1, 2))
# Scaling 1: species scoresscaled to the relative eigenvalues,
# sites are weighted averages of the species
plot(spe.cca,
scaling = 1,
display = c("sp", "lc", "cn"),
main = "Triplot CCA spe ~ env3 - scaling 1"
)
# Default scaling 2: site scores scaled to the relative
# eigenvalues, species are weighted averages of the sites
plot(spe.cca,
display = c("sp", "lc", "cn"),
main = "Triplot CCA spe ~ env3 - scaling 2"
)

```

```{r}
vif.cca(spe.cca)
```

En supprimant les valeurs supérieurs à 10, on obtient 
```{r}
spe <- data_bee_soil

spe.cca <- cca(spe ~ ., metal[c("As", "Cd", "Cr", "Pb", "Ni")])
summary(spe.cca) # Scaling 2 (default)
# Unadjusted and adjusted R^2 - like statistics
RsquareAdj(spe.cca)
```
```{r}
vif.cca(spe.cca)
```
```{r}
anova(spe.cca, by="term", permutations = how(nperm = 999))
anova(spe.cca, by="mar", permutations = how(nperm = 999))
anova(spe.cca, by="axis", permutations = how(nperm = 999))
```

```{r}

```

```{r}

```
