---
title: "cca"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
# Load the required packages
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(forcats )
library("readxl") 
```

Importation des données.
```{r Import}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

# Import
soil <- read_excel("Soil_R.xlsx")
SpecCondStat <- read_excel("SpecCondStat.xls")
```

```{r Nettoyage}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
soil$Site[soil$Site == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"

# retirer les sp abondantes (bombus)
# SCS <- filter(SCS, sp != "Bombus pascuorum")
# SCS <- filter(SCS, sp != "Bombus (Bombus)  sp.")
# SCS <- filter(SCS, sp != "Terrestribombus  sp.")
# SCS <- filter(SCS, sp != "Bombus vestalis")
# SCS <- filter(SCS, sp != "Bombus hypnorum")
# SCS <- filter(SCS, sp != "Bombus hortorum")
# SCS <- filter(SCS, sp != "Bombus pratorum")
# SCS <- filter(SCS, sp != "Bombus lapidarius")


#### Abbréger le nom des sites
# Liste des Potagers
Potagers <- c("Abbaye St-Denis", "Rue de l'Egalite", "Chasse Cambier", "Mel Legumes", "Gourmandes de la Procession", "Jean d'Avesnes", "Parc du bois de Mons", "Jardin Suspendu", "Ecole de l'Esperance", "Fond du petit marais")
# Liste des Parcs
Parcs <- c("Village des abeilles", "Siege social", "Parc du Beffroi", "Stievenart", "Parc Bonaert")

### Sol
## Metaux
# Créer une colonne Code en fonction des types de sites
soil$Code <- fct_collapse(
    soil$Site,
    "Potager" = Potagers,
    "Parc" = Parcs)

# Garder pour rownames
soil_site_name <- select(soil, Site)

# Garder les métaux seulement
metal <- soil[, c("As", "Cd", "Cr", "Cu", "Hg", "Pb", "Ni", "Zn")]
row.names(metal) <- soil_site_name$Site


```

```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + sites, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ sites + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)
```

```{r}
str(metal)
summary(metal)
```





Le pourcentage de variation expliqué par les axes est trop faible lorsque l'on utilise tous les axes.
```{r}
spe <- data_bee_sp
# le "." signifie contre toutes les var env; 1 : signifie aucune var env
spe.cca <- cca(spe ~ ., metal)
summary(spe.cca) # Scaling 2 (default)
# Unadjusted and adjusted R^2 - like statistics
RsquareAdj(spe.cca)
```


```{r}
vif.cca(spe.cca)
```

En supprimant les valeurs supérieurs à 10, on obtient 
```{r}
spe <- data_bee_sp
# c( "As", "Cr","Cd", "Cu", "Hg", "Pb","Ni", "Zn")
spe.cca <- cca(spe ~ ., metal[c( "As", "Cr","Cd", "Hg", "Pb","Ni")])
summary(spe.cca) # Scaling 2 (default)
# Unadjusted and adjusted R^2 - like statistics
RsquareAdj(spe.cca)
```

```{r}
par(mfrow = c(1, 2))
# Scaling 1: species scoresscaled to the relative eigenvalues,
# sites are weighted averages of the species
plot(spe.cca,
scaling = 1,
display = c("sp", "lc", "cn"),
main = "Triplot CCA spe ~ env3 - scaling 1"
)
# Default scaling 2: site scores scaled to the relative
# eigenvalues, species are weighted averages of the sites
plot(spe.cca,
display = c("sp", "lc", "cn"),
main = "Triplot CCA spe ~ env3 - scaling 2"
)

```

```{r}
# CCA scaling 1 biplot without species (using lc site scores)
plot(spe.cca,
scaling = 1,
display = c("lc", "cn"),
main = "Biplot CCA spe ~ env3 - scaling 1"
)
```



```{r}
# CCA scaling 2 biplot with species but without sites
plot(spe.cca,
scaling = 2,
display = c("sp", "cn"),
main = "Biplot CCA spe ~ env3 - scaling 2"
)
```

Permutation Tests in CCA,Forward Selection
and Parsimonious CCA
CCA results can be tested for significance by permutation, in the same way as RDA.
```{r}
# Permutation test of the overall analysis
anova(spe.cca, permutations = how(nperm = 999))
# Permutation test of each axis
anova(spe.cca, by = "axis", permutations = how(nperm = 999))

```

```{r}
# CCA-based forward selection using vegan's ordistep()
# This function allows the use of factors like 'slo' in env3
cca.step.forward <-
ordistep(cca(spe ~ 1, data = env3),
scope = formula(spe.cca),
direction = "forward",
permutations = how(nperm = 199))
```


```{r}
# calcul du VIF (corrélation entre variable)
#vif <- diag(solve(cor(X)))

# Variance inflation factors (VIF) in two RDAs
# First RDA of this Chapter: all environmental variables
# except dfs
vif.cca(spe.cca)
# Partial RDA – physiographic variables only
#vif.cca(spechem.physio)

```

```{r}
# CCA-based forward selection using vegan's ordistep()
# This function allows the use of factors like 'slo' in env3
cca.step.forward <-
ordistep(cca(spe ~ 1, data = env3),
scope = formula(spe.cca),
direction = "forward",
permutations = how(nperm = 199))
```



```{r}
## Parsimonious CCA using ele, oxy and bod
spe.cca.pars <- cca(spe ~  oxy + bdo, data = env3)
anova(spe.cca.pars, permutations = how(nperm = 999))
anova(spe.cca.pars, permutations = how(nperm = 999), by = "axis")
# R-square – like statistics
RsquareAdj(spe.cca.pars)
# Compare variance inflation factors
vif.cca(spe.cca)
vif.cca(spe.cca.pars)
```
Three-Dimensional Interactive Plots

```{r}
#library(vegan3d)
# Plot of the sites only (wa scores)
ordirgl(spe.cca.pars, type = "t", scaling = 1)
# Connect weighted average scores to linear combination scores
orglspider(spe.cca.pars, scaling = 1, col = "purple")
```

```{r}
# Plot the sites (wa scores) with a clustering result
# Colour sites according to cluster membership
# gr <- cutree(hclust(vegdist(spe.hel, "euc"), "ward.D2"), 4)
# ordirgl(spe.cca.pars,
# type = "t",
# scaling = 1,
# ax.col = "black",
# col = gr + 1
# )
# # Connect sites to cluster centroids
# orglspider(spe.cca.pars, gr, scaling = 1)
```


```{r}
# Complete CCA 3D triplot
ordirgl(spe.cca.pars, type = "t", scaling = 2)
orgltext(spe.cca.pars,
display = "species",
type = "t",
scaling = 2,
col = "cyan"
)
# Plot species groups (Jaccard dissimilarity, useable in R mode)
gs <-
cutree(
hclust(vegdist(t(spe), method = "jaccard"), "ward.D2"),
k = 4)
ordirgl(spe.cca.pars,
display = "species",
type = "t",
col = gs + 1)
```








