---
title: "Indice_diversité"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Load the required packages
library("readxl") 
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(tidyr)
library(ade4)
library(ggplot2)
library(iNEXT)
library(RColorBrewer)
library(reshape2)
```


Importation des données.
```{r Import}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
SpecCondStat <- read_excel("SpecCondStat.xls")
```

```{r Nettoyage}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "Apis mellifera"
SCS <- filter(SCS, sp != "Apis mellifera" )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus (Bombus)  sp."] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
```

```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + sites, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ sites + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)
```


```{r}
out <- iNEXT(as.data.frame(t(data_bee_sp)), q = c(0,1,2), datatype ="abundance", size=NULL, endpoint=NULL, knots=40, se=TRUE, conf=0.95, nboot=50) 
# Matrice Hill
DataInfotabee <-type.convert(out$DataInfo)

iNextEsttab <-type.convert(out$iNextEst)
AsyEsttab <-type.convert(out$AsyEst)

# Explication colonne estimateD() http://cran.nexr.com/web/packages/iNextPD/vignettes/Introduction.html
# the diversity estimate of order q (qPD), the 95% lower and upper confidence limits of diversity (qD.95.LCL, qD.95.UCL), and the sample coverage estimate (SC) along with the 95% lower and upper confidence limits of sample coverage (SC.95.LCL, SC.95.UCL). These sample coverage estimates with conf% confidence intervals are used for plotting the sample completeness curve and coverage-based R/E curves.

hill <- estimateD(t(data_bee_sp), base="coverage") # par défaut conf = 0.95
hillmatrix0= hill[hill[,"order"]==0,]
hillmatrix1= hill[hill[,"order"]==1,]
hillmatrix2= hill[hill[,"order"]==2,]
hillmatrix = hillmatrix0[,c(1,2,4)]
hillmatrix$SC0 = out$DataInfo$SC
hillmatrix[,c("N0","N0rU","N0rL")]=hillmatrix0[,c("qD","qD.UCL","qD.LCL")] # q = ordre, D = diversité, UCL = UpperConfidenceLimits, LCL = LowerCL
hillmatrix[,c("N1","N1rU","N1rL")]=hillmatrix1[,c("qD","qD.UCL","qD.LCL")] # Je retire NOr => N0, idem N1 et N2
hillmatrix[,c("N2","N2rU","N2rL")]=hillmatrix2[,c("qD","qD.UCL","qD.LCL")]
rownames(hillmatrix)= rownames(data_bee_sp)

bee.out <-DataInfotabee%>% select("SC","site") # SC = Sample Coverage
#rownames(bee.out)=rownamesmilieu
names(bee.out) <- c("Couverture", "site")
```

