---
title: "methods comparaison"
author: "Jordan Benrezkallah"
date: "4/18/2022"
output: pdf_document
---

```{r library, include=FALSE}
library("readxl")
library(dplyr)
#library(ggpubr)
library(tidyverse)
library(knitr)
library(ggplot2)
library(ggpubr)
library(ggthemes)
library(viridis)
library(RColorBrewer)
```

## Importation des données
```{r Import, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2/Traits abeilles")

# Import
soil <- read_excel("Soil_R.xlsx")
valeur_seuil <- read_excel("valeur_seuil.xlsx")

soil$Site[soil$Site == "Les Gourmandes de la Procession"] <- "Gourmandes"
```

Matrice metal X site
```{r}
# Garder pour rownames
soil_site_name <- select(soil, Site)

# Garder les métaux et sites
metal <- soil[, c("Site", "As", "Cd", "Cr", "Cu", "Hg", "Pb", "Ni", "Zn")]
```

```{r}
df <- metal
df <- gather(df, key="pollution", value="qte", 2:9)
```


```{r site}
# 8 polluants
nb.cols <- 8
mycolors <- colorRampPalette(brewer.pal(8, "Set2"))(nb.cols)
# Valeur seuil a afficher (III : Résidentiel)
# hline_value <- valeur_seuil$Residentiel
# Valeur seuil a afficher (II : Agricole)
# ça a plus de sens vu que le but est de cultiver des fruits et légumes
hline_value <- valeur_seuil$Agricole


ggplot(df, aes(fill=pollution, y=qte, x=Site)) + 
  geom_hline(yintercept = hline_value, linetype = 2, color = mycolors, lwd = 0.2) +
  geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
  labs(x = "", y = "Quantité [mg/kg de MS]",fill = "Métaux lourd",fontface = "bold") + 
  scale_fill_brewer(palette="Set2") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Study site
        axis.title.y = element_text(face="bold", size = 10), # Quantité
        axis.text.x = element_text(angle = 90,face="bold", color= "black", size=8), # Site
        axis.text.y = element_text(face="bold", color= "black", size=5), # 
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.title = element_text(size=8, face="bold"), # "Métaux lourd" dans la légende
        legend.text = element_text(size=8, face="bold"), # les Métaux lourd dans la légende
        legend.position="bottom") 
```

```{r site}
# Retirer les polluants avec d'importante quantité
df <- select(metal, -Pb, -Zn)
df <- gather(df, key="pollution", value="qte", 2:7)

# 8 polluants
nb.cols <- 6
mycolors <- colorRampPalette(brewer.pal(6, "Set2"))(nb.cols)

# Valeur seuil a afficher (III : Résidentiel)
# hline_value <- valeur_seuil$Residentiel
# Valeur seuil a afficher (II : Agricole)
# ça a plus de sens vu que le but est de cultiver des fruits et légumes
hline_value <- filter(valeur_seuil, Polluant != "Zinc" & Polluant != "Plomb")
hline_value <- hline_value$Agricole


ggplot(df, aes(fill=pollution, y=qte, x=Site)) +
  geom_hline(yintercept = hline_value, linetype = 2, color = mycolors, lwd = 0.3) +
  geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
  labs(x = "", y = "Quantité [mg/kg de MS]",fill = "Métaux lourd",fontface = "bold") +
  scale_fill_brewer(palette="Set2") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Study site
        axis.title.y = element_text(face="bold", size = 10), # Quantité
        axis.text.x = element_text(angle = 90,face="bold", color= "black", size=8), # Site
        axis.text.y = element_text(face="bold", color= "black", size=5), #
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.title = element_text(size=8, face="bold"), # "Métaux lourd" dans la légende
        legend.text = element_text(size=8, face="bold"), # les Métaux lourd dans la légende
        legend.position="bottom")
ggsave(filename = "histo_metal_2.pdf", device = cairo_pdf)
```

```{r site}
# Garder seulement polluant avec faible quantité
df <- select(metal, Site, Hg, Cd)
df <- gather(df, key="pollution", value="qte", 2:3)

# 2 polluants
nb.cols <- 8
mycolors <- colorRampPalette(brewer.pal(n=8, "Set2"))(nb.cols+1) # n = 3 minimum, faut chippoter
mycolors <- mycolors[c(1,2)] 

# Valeur seuil a afficher (II : agricole)
valeur_seuil <- filter(valeur_seuil, Polluant == "Cadmium" | Polluant == "Mercure")
hline_value <- valeur_seuil$Agricole


ggplot(df, aes(fill=pollution, y=qte, x=Site)) +
  geom_hline(yintercept = hline_value, linetype = 2, color = mycolors, lwd = 0.5) +
  geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
  labs(x = "", y = "Quantité [mg/kg de MS]",fill = "Métaux lourd",fontface = "bold") +
  scale_fill_brewer(palette="Set2") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Study site
        axis.title.y = element_text(face="bold", size = 10), # Quantité
        axis.text.x = element_text(angle = 90,face="bold", color= "black", size=8), # Site
        axis.text.y = element_text(face="bold", color= "black", size=5), #
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.title = element_text(size=8, face="bold"), # "Métaux lourd" dans la légende
        legend.text = element_text(size=8, face="bold"), # les Métaux lourd dans la légende
        legend.position="bottom")

# ggsave(filename = "histo_metal_3.pdf", device = cairo_pdf)
```


```{r site}
# 8 polluants : As
df <- select(metal, Site, As)
df <- gather(df, key="pollution", value="qte", 2)
hline_value <- filter(valeur_seuil, Polluant == "Arsenic" )
hline_value <- hline_value$Agricole

ggplot(df, aes(fill=pollution, y=qte, x=Site)) + 
  geom_hline(yintercept = hline_value, linetype = 2, color = mycolors[1], lwd = 0.2) +
  geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
  labs(x = "", y = "Quantité [mg/kg de MS]",fill = "Métaux lourd",fontface = "bold") + 
  scale_fill_brewer(palette="Set2") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Study site
        axis.title.y = element_text(face="bold", size = 10), # Quantité
        axis.text.x = element_text(angle = 90,face="bold", color= "black", size=8), # Site
        axis.text.y = element_text(face="bold", color= "black", size=5), # 
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.title = element_text(size=8, face="bold"), # "Métaux lourd" dans la légende
        legend.text = element_text(size=8, face="bold"), # les Métaux lourd dans la légende
        legend.position="bottom") 

ggsave(filename = "histo_metal_1.pdf", device = cairo_pdf)
```

```{r site}
# 8 polluants : As
# df <- select(metal, Site, Cd)
# df <- gather(df, key="pollution", value="qte", 2)
# hline_value <- filter(valeur_seuil, Polluant == "Cadmium" )
# hline_value <- hline_value$Agricole
# 
# ggplot(df, aes(fill=mycolors[3], y=qte, x=Site)) + 
#   geom_hline(yintercept = hline_value, linetype = 2, color = mycolors[2], lwd = 0.2) +
#   geom_bar(position="dodge", stat="identity", colour="black", size = 0.3) +
#   labs(x = "", y = "Quantité [mg/kg de MS]",fill = "Métaux lourd",fontface = "bold") + 
#   scale_fill_brewer(palette="Set2") +
#   theme(axis.title.x = element_text(face="bold", size = 10), # Study site
#         axis.title.y = element_text(face="bold", size = 10), # Quantité
#         axis.text.x = element_text(angle = 90, face="bold", color= "black", size=8), # Site
#         axis.text.y = element_text(face="bold", color= "black", size=5), # 
#         panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
#         panel.background = element_rect(fill='white', colour='black'),
#         legend.title = element_text(size=8, face="bold"), # "Métaux lourd" dans la légende
#         legend.text = element_text(size=8, face="bold"), # les Métaux lourd dans la légende
#         legend.position="bottom") 
# 
# ggsave(filename = "histo_metal_2.pdf", device = cairo_pdf)
```