---
title: "azote"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

---
title: "acp metaux"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
# Load the required packages
library("readxl") 
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(ggfortify)
library(tidyr)
library(plotly)
library(ggplot2)
library(taxize)
library(iNEXT)
library(RColorBrewer)
library(reshape2)
```

Importation des données.
```{r Import}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

soil <- read_excel("Soil_R.xlsx")
```

```{r abbréger nom des sites}
#### Abbréger le nom des sites
# Remplacement du noms de sites
soil$Site[soil$Site == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"

# Liste des Potagers
Potagers <- c("Abbaye St-Denis", "Rue de l'Egalite", "Chasse Cambier", "Mel Legumes", "Gourmandes de la Procession", "Jean d'Avesnes", "Parc du bois de Mons", "Jardin Suspendu", "Ecole de l'Esperance", "Fond du petit marais")
# Liste des Parcs
Parcs <- c("Village des abeilles", "Siege social", "Parc du Beffroi", "Stievenart", "Parc Bonaert")

### Sol
# Créer une colonne Code en fonction des types de sites
soil$Code <- fct_collapse(
    soil$Site,
    "Potager" = Potagers,
    "Parc" = Parcs)

# substring prend les premiers caractères, abbreviate abrège comme il le sent
soil$code_site <- paste(substring(soil$Code, 0,3),"-", abbreviate(soil$Site))
# retirer les apostrophes
soil$code_site <- gsub("'", "", soil$code_site)
```


```{r Preparation des données }
# Preparation des données 
### Sol
# Azote (Nitrogen) 
# Nitrate NO3, ammonium NH4, azote total N
azote <- soil[,9:12]
azote <- azote[,-1]
row.names(azote) <- soil_site_name$code_site
```

```{r}

a <- azote

# Calcul PCA avec vegan::rda() 
#pca_m <- rda(m)
# Mettre à l'échelle (=?réduire donnée) comment centrer les données
pca_a1 <- rda(a, scaling = TRUE)

# Centrer et réduire 
#scale (a, center = TRUE, scale = TRUE)

# Calcul PCA standardized avec vegan::prcomp() ACP normée (centré et réduite)
pca_a2 <- prcomp(a, center = TRUE, scale = TRUE)

# rda() donne plus d'information, score sp et site
summary(pca_a1)
s <- summary(pca_a2)
screeplot(pca_a2, bstick = TRUE)


biplot(pca_a2, scaling = "sites")
autoplot(pca_a2, data = soil, colour = "Code", label = TRUE, label.size = 3, shape = FALSE,
         loadings = TRUE, loadings.colour = 'blue',
         loadings.label = TRUE, frame = TRUE)
```

```{r}
# Code d'origine 
# https://www.benjaminbell.co.uk/2018/02/principal-components-analysis-pca-in-r.html
p <- pca_a2
# Renommer pour avoir les labels avec abréviation sans apostrophe
rownames(p$x) <- gsub("'", "", abbreviate(soil$Site))

pch.group <- c(rep(21, times=10), rep(22, times=5))
col.group <- c(rep("skyblue2", times=10), rep("gold", times=5))

plot(p$x[,1], p$x[,2], xlab=paste("PCA 1 (", round(s$importance[2]*100, 1), "%)", sep = ""), 
     ylab=paste("PCA 2 (", round(s$importance[5]*100, 1), "%)", sep = ""), pch=pch.group, col="black", bg = col.group, cex=2, las=1, asp=1)
plot(p$x[,1], p$x[,2], xlab=paste("PCA 1 (", round(s$importance[2]*100, 1), "%)", sep = ""), ylab=paste("PCA 2 (", round(s$importance[5]*100, 1), "%)", sep = ""), pch=pch.group, col="black", bg=col.group, cex=2, las=1, asp=1)

# Add grid lines
abline(v=0, lty=2, col="grey50")
abline(h=0, lty=2, col="grey50")
# Add labels
text(p$x[,1], p$x[,2], labels=row.names(p$x), pos=c(1,3,4,2), font=2)

# Add legend
legend("bottomrigh", legend=c("Potager", "Parc"), col="black", pt.bg=c("skyblue2", "gold"), pch=c(21, 22), pt.cex=1.5)
# Get co-ordinates of variables (loadings), and multiply by 10
l.x <- p$rotation[,1]*2
l.y <- p$rotation[,2]*2
# Draw arrows
arrows(x0=0, x1=l.x, y0=0, y1=l.y, col="red", length=0.15, lwd=1.5)
# Label position
l.pos <- l.y # Create a vector of y axis coordinates
lo <- which(l.y < 0) # Get the variables on the bottom half of the plot
hi <- which(l.y > 0) # Get variables on the top half
# Replace values in the vector
l.pos <- replace(l.pos, lo, "1")
l.pos <- replace(l.pos, hi, "3")
# Variable labels
text(l.x, l.y, labels=row.names(p$rotation), col="red", pos=l.pos)
```


