---
title: "Indice_diversité"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# Load the required packages
library("readxl") 
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(tidyr)
library(ade4)
#library(adegraphics)
#library(adespatial)
#library(vegetarian)
library(ggplot2)
library(FD)
library(taxize)
library(iNEXT)
library(RColorBrewer)
library(reshape2)

# Chargé la fonction panelutils
source ('https://raw.githubusercontent.com/zdealveindy/anadat-r/master/scripts/NumEcolR2/panelutils.R')
```


Importation des données.
```{r Import}
# Import
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2")

SpecCondStat <- read_excel("SpecCondStat.xls")


```

```{r Nettoyage}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
```

```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + sites, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ sites + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)

```



```{r}
#Isolation du chunk
bee <- data_bee_sp
# Nombre d'espèces observées dans les 15 sites
(bee.nbsp <- specnumber(bee))
# Sites avec une richesse en espèces minimale et maximale observée
bee.nbsp[bee.nbsp == min(bee.nbsp)]
bee.nbsp[bee.nbsp == max(bee.nbsp)]
range(bee.nbsp)
# Abondance totale dans les 15 sites
(bee.abund <- rowSums(bee))
range(bee.abund)
# Abondance dans les sites avec le plus petit nombre d'espèces
bee.abund[bee.nbsp == min(bee.nbsp)]
# Abondance dans les sites avec le plus grand nombre d'espèces
bee.abund[bee.nbsp == max(bee.nbsp)]
# Nombre d'espèces dans les sites avec la plus petite abondance
bee.nbsp[bee.abund == min(bee.abund)]
# Nombre d'espèces dans les sites avec la plus grande abondance
bee.nbsp[bee.abund == max(bee.abund)]

```


```{r}
# Raréfaction à 33 individus (Parc Bonaert a le plus petit nbr d'individus)
bee.rare33 <- rarefy(bee, sample = 33)
# Comparer le classement de la richesse entre les sites observés et raréfiés
sort(bee.nbsp)
sort(round(bee.rare33)) 
# Sites avec une richesse en espèces minimale et maximale estimée
bee.rare33[bee.rare33 == min(bee.rare33)]
bee.rare33[bee.rare33 == max(bee.rare33)]
# Site observé avec la plus petite richesse prédite en espèces
bee[which(bee.rare33 == min(bee.rare33)),]
# Site observé avec la plus grande richesse d'espèces prédite
bee[which(bee.rare33 == max(bee.rare33)),]

```

```{r}
rarecurve(bee, 
          step = 1,
          xlab = "Nombre d'individus (Taille d'échantillon)", 
          ylab = "Nombre d'espèces observé (richesse)", 
          label = TRUE, 
          border = NA,
          col = mycolors,
          cex = 0.5, bg = "red" )
abline(v = 33, col="gray")

```

```{r}
######################################rarefaction

raremax <- min(rowSums(data_bee_sp))
lty <- c("solid", "dashed", "longdash", "dotdash")
rarecurve(data_bee_sp, step = 1, xlab = "Nombre d'individus collectés", ylab = "Nombre d'espèces observées", col = mycolors, label = TRUE, border = NA, main = "Courbes de raréfaction des diférents types de milieux")
```

```{r}
# https://stat.ethz.ch/pipermail/r-sig-ecology/2018-December/005867.html
#data(BCI)
out <- rarecurve(bee, step = 1, sample = 33, label = TRUE, col = "blue")
names(out) <- paste("species", 1:nrow(bee), sep = "")

# Coerce data into "long" form.
protox <- mapply(FUN = function(x, y) {
  mydf <- as.data.frame(x)
  colnames(mydf) <- "value"
  mydf$species <- y
  mydf$subsample <- attr(x, "Subsample")
  mydf
}, x = out, y = as.list(names(out)), SIMPLIFY = FALSE)

xy <- do.call(rbind, protox)
rownames(xy) <- NULL  # pretty

# Plot.
ggplot(xy, aes(x = subsample, y = value, color = species)) +
    theme_bw() +
    theme(legend.position = "none") +  # ggplotly doesn't respect scales?
    geom_line() +
  geom_vline(xintercept = 33, color = "gray") +
    labs(x = "Nombre d'individus collectées (abondance observée)", y = "Nombre d'espèces observé (richesse observée)") +
  theme(axis.title.x = element_text(face="bold", size = 20), # Titre axe x
        axis.title.y = element_text(face="bold", size = 20), # Titre axe y
        axis.text.x = element_text(face="bold", color= "black", size=15, hjust=0), # Echelle x
        axis.text.y = element_text(face="bold", color= "black", size=15), # Echelle y
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.position = "none")


ggplotly(
  ggplot(xy, aes(x = subsample, y = value, color = species)) +
    theme_bw() +
    theme(legend.position = "none") +  # ggplotly doesn't respect scales?
    geom_line() +
    labs(x = "Nombre d'individus collectées (abondance observée)", y = "Nombre d'espèces observé (richesse observée)") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Titre axe x
        axis.title.y = element_text(face="bold", size = 10), # Titre axe y
        axis.text.x = element_text(face="bold", color= "black", size=10, hjust=0), # Echelle x
        axis.text.y = element_text(face="bold", color= "black", size=10), # Echelle y
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.position = "none") 
)
```




```{r}
Bee_inext <- as.data.frame(t(data_bee_sp))
my_list2 <- list()  

for(i in 1:ncol(Bee_inext)) {             # Using for-loop to add columns to list
  my_list2[[i]] <- Bee_inext[ , i]
}
```



```{r}
out <- iNEXT(as.data.frame(t(data_bee_sp)), q = c(0,1,2), datatype ="abundance", size=NULL, endpoint=NULL, knots=40, se=TRUE, conf=0.95, nboot=50) 


```

```{r}
nb.cols <- 15
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(nb.cols)

ggiNEXT(out, type=2, se=FALSE, color.var="site" ) +
  labs(title = "", y = 'Taux de couverture', x = "Nombre d'individus", col ="Site") +
  scale_colour_manual(values = mycolors)  +
  #scale_color_brewer(palette = "Set1") +
  theme(axis.title.x = element_text(face="bold", size = 10), # Titre axe x
        axis.title.y = element_text(face="bold", size = 10), # Titre axe y
        axis.text.x = element_text(face="bold", color= "black", size=10, hjust=0), # Echelle x
        axis.text.y = element_text(face="bold", color= "black", size=10), # Echelle y
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.position = "bottom") 
```


```{r}
# Matrice Hill
DataInfotabee <-type.convert(out$DataInfo)

iNextEsttab <-type.convert(out$iNextEst)
AsyEsttab <-type.convert(out$AsyEst)

# Explication colonne estimateD() http://cran.nexr.com/web/packages/iNextPD/vignettes/Introduction.html
# the diversity estimate of order q (qPD), the 95% lower and upper confidence limits of diversity (qD.95.LCL, qD.95.UCL), and the sample coverage estimate (SC) along with the 95% lower and upper confidence limits of sample coverage (SC.95.LCL, SC.95.UCL). These sample coverage estimates with conf% confidence intervals are used for plotting the sample completeness curve and coverage-based R/E curves.

hill <- estimateD(t(data_bee_sp), base="coverage") # par défaut conf = 0.95
hillmatrix0= hill[hill[,"order"]==0,]
hillmatrix1= hill[hill[,"order"]==1,]
hillmatrix2= hill[hill[,"order"]==2,]
hillmatrix = hillmatrix0[,c(1,2,4)]
hillmatrix$SC0 = out$DataInfo$SC
hillmatrix[,c("N0","N0rU","N0rL")]=hillmatrix0[,c("qD","qD.UCL","qD.LCL")] # q = ordre, D = diversité, UCL = UpperConfidenceLimits, LCL = LowerCL
hillmatrix[,c("N1","N1rU","N1rL")]=hillmatrix1[,c("qD","qD.UCL","qD.LCL")] # Je retire NOr => N0, idem N1 et N2
hillmatrix[,c("N2","N2rU","N2rL")]=hillmatrix2[,c("qD","qD.UCL","qD.LCL")]
rownames(hillmatrix)= rownames(data_bee_sp)

bee.out <-DataInfotabee%>% select("SC","site") # SC = Sample Coverage
#rownames(bee.out)=rownamesmilieu
names(bee.out) <- c("Couverture", "site")
```


```{r}
# Graphique nombre de Hill
graphhill <- select(hillmatrix,N0,N1,N2)
#rownames(graphhill)= rownames(milieutab)
graphhill <- tibble::rownames_to_column(graphhill, "type")

graphhill<-reshape::melt(graphhill)
graphhill<-graphhill %>%group_by(type)

nb.cols <- 15
mycolors <- colorRampPalette(brewer.pal(8, "Set1"))(nb.cols)

ggplot(graphhill,aes(x = variable, y= value, group = type, color = type))   +
  geom_line()+ 
  geom_point()+
  xlab("Nombre de Hill") +
  ylab("Nombre d'espèces observées")  +
  scale_y_continuous(breaks = round(seq(min(0), max(200), by = 4),1))+
  labs(
    title = "",
    subtitle = "",
    caption = "") +
  #guides(fill = guide_legend(title = "Sites")) + # Titre légende (marche slmt pour Heatmap)
  scale_color_discrete("")+ # Titre légende
  scale_colour_manual(values = mycolors)  +
  theme(
    plot.title = element_text(hjust = 0.5, size=18),
    plot.subtitle = element_text(face = ),
    plot.caption = element_text(face = "italic", size = 9),
    axis.title.x =element_text(size = 15 ), 
    axis.title.y =element_text(size = 15),
    axis.text.x=element_text(size = 12),
    axis.text.y=element_text(size = 13),
    legend.text =element_text(size = 12),
    legend.title =element_text(size = 14),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.background = element_rect(fill='white', colour='black'))
```



```{r}
# Boxplot

abond <- out

DataInfotab <-type.convert(abond$DataInfo)
iNextEsttab <-type.convert(abond$iNextEst)
AsyEsttab <-type.convert(abond$AsyEst)

hill <- estimateD(t(data_bee_sp), base="coverage")
hillmatrix0= hill[hill[,"order"]==0,]
hillmatrix1= hill[hill[,"order"]==1,]
hillmatrix2= hill[hill[,"order"]==2,]
hillmatrix = hillmatrix0[,c(1,2,4)]
hillmatrix$SC0 = abond$DataInfo$SC
hillmatrix[,c("H0r","H0rU","H0rL")]=hillmatrix0[,c("qD","qD.UCL","qD.LCL")]
hillmatrix[,c("H1r","H1rU","H1rL")]=hillmatrix1[,c("qD","qD.UCL","qD.LCL")]
hillmatrix[,c("H2r","H2rU","H2rL")]=hillmatrix2[,c("qD","qD.UCL","qD.LCL")]
rownames(hillmatrix)=rownames(data_bee_sp) 

bee.abond <-DataInfotab%>% select( "SC","site")
rownames(bee.abond)=rownames(data_bee_sp)
rename(bee.abond,  "Couverture" = "SC") -> bee.abond


beecouv <- left_join (bee.abond, type , by=c("site"="nom"))
beecouv$Dummy <- factor("")
```

```{r}

is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}
beecouv %>%
  group_by(site) %>%
  mutate(outlier = ifelse(is_outlier(Couverture), Couverture, as.numeric(NA))) %>%
  ggplot(.,aes(x = Dummy,y=Couverture))   +
  geom_boxplot(fill = "#56B4E9" )+ 
  geom_dotplot(binaxis='y', stackdir='center', dotsize=0.5)+
  xlab("") +
  ylab("Taux de couverture")+
  geom_text(aes(label = outlier ,y = Couverture),nudge_x = 0.08, size =5)+
  labs(title = "", subtitle = "", caption = "") +
  theme(axis.title.x = element_text(face="bold", size = 12), # Titre axe x
        axis.title.y = element_text(face="bold", size = 15), # Titre axe y
        axis.text.x = element_text(face="bold", color= "black", size=10, hjust=0), # Echelle x
        axis.text.y = element_text(face="bold", color= "black", size=10), # Echelle y
        panel.grid.major = element_blank(),panel.grid.minor = element_blank(),
        panel.background = element_rect(fill='white', colour='black'),
        legend.position = "none") 



```



















```{r}
# On importe un jeu de donn?es test : les poissons de la rivi?re Doubs
data (doubs)
spe <- doubs$fish# Une rivi?re, 30 sites, une longue liste de poissons
env <- doubs$env # La m?me rivi?re, les m?mes sites, mais de nombreux types de descripteurs environnementaux
?doubs #Plus d'infos
# On retire le site ! car il est vide !
spe = spe[-8,]
env = env[-8,]
```


Pielou evenness is biased because it is systematically positively correlated with species richness, as shown in the correlation matrix (legendre)
```{r}
# Get help on the diversity() function
?diversity
# Compute alpha diversity indices of the fish communities
N0 <- rowSums(spe > 0) # Species richness
N0 <- specnumber(spe) # Species richness (alternate)
H <- diversity(spe) # Shannon entropy (base e)
Hb2 <- diversity(spe, base = 2) # Shannon entropy (base 2)
N1 <- exp(H) # Shannon diversity (base e)
# (number of abundant species)
N1b2 <- 2^Hb2 # Shannon diversity (base 2)
N2 <- diversity(spe, "inv") # Simpson diversity
# (number of dominant species)
J <- H / log(N0) # Pielou evenness
E10 <- N1 / N0 # Shannon evenness (Hill's ratio)
E20 <- N2 / N0 # Simpson evenness (Hill's ratio)
(div <- data.frame(N0, H, Hb2, N1, N1b2, N2, E10, E20, J))
```

```{r}

# Compute alpha diversity indices of the fish communities
N0_rs <- rowSums(data_bee_sp > 0) # Species richness
N0 <- specnumber(data_bee_sp) # Species richness (alternate)
H <- diversity(data_bee_sp) # Shannon entropy (base e)
Hb2 <- diversity(data_bee_sp, base = 2) # Shannon entropy (base 2)
N1 <- exp(H) # Shannon diversity (base e)
# (number of abundant species)
N1b2 <- 2^Hb2 # Shannon diversity (base 2)
N2 <- diversity(data_bee_sp, "inv") # Simpson diversity
# (number of dominant species)
J <- H / log(N0) # Pielou evenness
E10 <- N1 / N0 # Shannon evenness (Hill's ratio)
E20 <- N2 / N0 # Simpson evenness (Hill's ratio)
(div <- data.frame(N0_rs,N0, N1, H, Hb2,  N1b2, N2, E10, E20, J))
```


```{r}
# Correlations among diversity indices
cor(div)
pairs(div[-1, ],
lower.panel = panel.smooth,
upper.panel = panel.cor,
diag.panel = panel.hist,
main = "Pearson Correlation Matrix"
)
```

```{r}
data(mite)
# Number of species in the 70 moss or soil cores
t<- (mite.nbsp <- specnumber(mite))
t
# Cores with minimum and maximum observed species richness
mite.nbsp[mite.nbsp == min(mite.nbsp)]
mite.nbsp[mite.nbsp == max(mite.nbsp)]
range(mite.nbsp)
# Total abundance in the 70 cores
(mite.abund <- rowSums(mite))
range(mite.abund)
# Abundance in the cores with smallest number of species
mite.abund[mite.nbsp == min(mite.nbsp)]
# Abundance in the core with largest number of species
mite.abund[mite.nbsp == max(mite.nbsp)]
# Number of species in the core with smallest abundance
mite.nbsp[mite.abund == min(mite.abund)]
# Number of species in the core with largest abundance
mite.nbsp[mite.abund == max(mite.abund)]
# Rarefaction to 80 individuals
mite.rare80 <- rarefy(mite, sample = 80)
# Compare ranking of observed and rarefied cores
sort(mite.nbsp)
sort(round(mite.rare80))
# Cores with minimum and maximum estimated species richness
mite.rare80[mite.rare80 == min(mite.rare80)]
mite.rare80[mite.rare80 == max(mite.rare80)]
# Observed core with smallest predicted species richness
mite[which(mite.rare80 == min(mite.rare80)),]
# Observed core with largest predicted species richness
mite[which(mite.rare80 == max(mite.rare80)),]
```

```{r}
# Nombre d'espèces dans les 15 sites
(mite.nbsp <- specnumber(mite))
# Sites avec une richesse en espèces minimale et maximale observée
mite.nbsp[mite.nbsp == min(mite.nbsp)]
mite.nbsp[mite.nbsp == max(mite.nbsp)]
range(mite.nbsp)
# Abondance totale dans les 15 sites
(mite.abund <- rowSums(mite))
range(mite.abund)
# Abondance dans les sites avec le plus petit nombre d'espèces
mite.abund[mite.nbsp == min(mite.nbsp)]
# Abondance dans les sites avec le plus grand nombre d'espèces
mite.abund[mite.nbsp == max(mite.nbsp)]
# Nombre d'espèces dans les sites avec la plus petite abondance
mite.nbsp[mite.abund == min(mite.abund)]
# Nombre d'espèces dans les sites avec la plus grande abondance
mite.nbsp[mite.abund == max(mite.abund)]

```

```{r}
# Rarefaction to 80 individuals
mite.rare80 <- rarefy(mite, sample = 80)
# Compare ranking of observed and rarefied cores
sort(mite.nbsp)
sort(round(mite.rare80))
# Cores with minimum and maximum estimated species richness
mite.rare80[mite.rare80 == min(mite.rare80)]
mite.rare80[mite.rare80 == max(mite.rare80)]
# Observed core with smallest predicted species richness
mite[which(mite.rare80 == min(mite.rare80)),]
# Observed core with largest predicted species richness
mite[which(mite.rare80 == max(mite.rare80)),]
```

