---
title: "IUCN"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

## Chargement des paquets
```{r Library, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
library("readxl") 
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis) # couleur daltonien
library(tidyr) # fonction gather
library("writexl")
```

## Importation des données
```{r Import, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW/Traits abeilles")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2/Traits abeilles")

SpecCondStat <- read_excel("SpecCondStat_traits.xls")

# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "Site" = "TOPO" ) -> SCS
rename(SCS, "genus" = "SPEC.GEN" ) -> SCS
rename(SCS, "familly" = "SPEC.GR2" ) -> SCS

# Retirer les observations contenant l'espèce : "Apis mellifera"
SCS <- filter(SCS, sp != "Apis mellifera" )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus (Bombus)  sp."] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$genus[SCS$genus == "Chalicodoma"] <- "Megachile"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$Site[SCS$Site == "Les Gourmandes de la Procession"] <- "Gourmandes"

# Réécriture des noms de familles
SCS$familly[SCS$familly == "ANDRENIDAE"] <- "Andrenidae"
SCS$familly[SCS$familly == "APIDAE"] <- "Apidae"
SCS$familly[SCS$familly == "COLLETIDAE"] <- "Colletidae"
SCS$familly[SCS$familly == "HALICTIDAE"] <- "Halictidae"
SCS$familly[SCS$familly == "MEGACHILIDAE"] <- "Megachilidae"
SCS$familly[SCS$familly == "MELITTIDAE"] <- "Melittidae"
```

```{r}
SCS %>%
  group_by(sp, Site, genus, familly, Lectism) %>%
  count(sp) -> df
df$N <- df$n
```

Par espèce
```{r}
# Addition des genres avec le lectisme (oligo ou poly)
lectism <- aggregate(N ~ sp + Lectism, data = df, sum)
```

```{r Espèce}
### Abondance des sp
# Socialité abondance-espèces
lectism_abu <-  spread(lectism, key = Lectism , value = N)
# Ajoute une ligne total
lectism_abu <- janitor::adorn_totals(lectism_abu)
# Ajoute une colonne total
lectism_abu$Total <- rowSums(lectism_abu[, c("Oligolectic", "Polylectic")])

lectism_abu$Oligolectic <- as.integer(lectism_abu$Oligolectic)
lectism_abu$Polylectic <- as.integer(lectism_abu$Polylectic)


# Pourcentage abon Oligolectic
pct_abu_oli <- round(lectism_abu[nrow(lectism_abu), "Oligolectic"]/lectism_abu[nrow(lectism_abu), "Total"], digits = 2)
# Pourcentage abon Polylectic
pct_abu_pol <- round(lectism_abu[nrow(lectism_abu), "Polylectic"]/lectism_abu[nrow(lectism_abu), "Total"], 2)


lectism_abu[nrow(lectism_abu) + 1,] = c("Pourcentage", pct_abu_oli,pct_abu_pol,"")




### Richesse 
lectism_rich <- lectism
# Changer tous les chiffres d'abondances par 1
lectism_rich$N[lectism_rich$N > 0] <- 1  
# Tableau avec colonne (Solitaire, clepto, ...)
lectism_rich <-  spread(lectism_rich, key = Lectism , value = N)
# Ajoute une ligne total
lectism_rich <- janitor::adorn_totals(lectism_rich)
# Ajoute une colonne total
lectism_rich$Total <- rowSums(lectism_rich[, c("Oligolectic", "Polylectic")])

# Pourcentage rich Clepto
pct_rich_oli <- round(lectism_rich[nrow(lectism_rich), "Oligolectic"]/lectism_rich[nrow(lectism_rich), "Total"], digits = 2)
# Pourcentage rich Polylectic
pct_rich_pol <- round(lectism_rich[nrow(lectism_rich), "Polylectic"]/lectism_rich[nrow(lectism_rich), "Total"], 2)


lectism_rich[nrow(lectism_rich) + 1,] = c("Pourcentage", pct_rich_oli, pct_rich_pol, "")
```
Par genre
```{r}
# Addition des genres avec la socialité
lectism_gen <- aggregate(N ~ genus + Lectism, data = df, sum)
```

```{r}
### Abondance des genres
# Socialité abondance-espèces
lectism_gen_abu <-  spread(lectism_gen, key = Lectism , value = N)
# Ajoute une ligne total
lectism_gen_abu <- janitor::adorn_totals(lectism_gen_abu)
# Ajoute une colonne total
lectism_gen_abu$Total <- rowSums(lectism_gen_abu[, c("Oligolectic", "Polylectic")])

# Pourcentage abon Oligolectic
pct_abu_oli <- round(lectism_gen_abu[nrow(lectism_gen_abu), "Oligolectic"]/lectism_gen_abu[nrow(lectism_gen_abu), "Total"], digits = 2)
# Pourcentage abon Polylectic
pct_abu_pol <- round(lectism_gen_abu[nrow(lectism_gen_abu), "Polylectic"]/lectism_gen_abu[nrow(lectism_gen_abu), "Total"], 2)


lectism_gen_abu[nrow(lectism_gen_abu) + 1,] = c("Pourcentage", pct_abu_oli,pct_abu_pol,pct_abu_par,pct_abu_sol,"")


### Richesse des genres
lectism_gen_rich <- lectism_gen
# Changer tous les chiffres d'abondances par 1
lectism_gen_rich$N[lectism_gen_rich$N > 0] <- 1  
# Tableau avec colonne (Polylectic, Oligolectic, ...)
lectism_gen_rich <-  spread(lectism_gen_rich, key = Lectism , value = N)
# Ajoute une ligne total
lectism_gen_rich <- janitor::adorn_totals(lectism_gen_rich)
# Ajoute une colonne total
lectism_gen_rich$Total <- rowSums(lectism_gen_rich[, c("Oligolectic", "Polylectic")])

# Pourcentage rich Oligolectic
pct_rich_oli <- round(lectism_gen_rich[nrow(lectism_gen_rich), "Oligolectic"]/lectism_gen_rich[nrow(lectism_gen_rich), "Total"], digits = 2)
# Pourcentage rich Polylectic
pct_rich_pol <- round(lectism_gen_rich[nrow(lectism_gen_rich), "Polylectic"]/lectism_gen_rich[nrow(lectism_gen_rich), "Total"], 2)


lectism_gen_rich[nrow(lectism_gen_rich) + 1,] = c("Pourcentage", pct_rich_oli,pct_rich_pol,pct_rich_par,pct_rich_sol,"")
```

```{r}
my_df <- list(lectism, lectism_abu, lectism_rich, lectism_gen_abu, lectism_gen_rich)
# Exportation tableur Excel
# Brute
write_xlsx(my_df , "D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/Output/lectism.xlsx")
```


