---
title: "IUCN"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

## Chargement des paquets
```{r Library, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
library("readxl") 
library(dplyr)
library(plotly)
library(ggplot2)
library(viridis) # couleur daltonien
library(tidyr) # fonction gather
library("writexl")
```

## Importation des données
```{r Import, message=FALSE, warning=FALSE, include=FALSE, results='hide', paged.print=FALSE}
# Tour PC
setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW/Traits abeilles")
# Laptop
#setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW2/Traits abeilles")

SpecCondStat <- read_excel("SpecCondStat_traits.xls")

# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "Site" = "TOPO" ) -> SCS
rename(SCS, "genus" = "SPEC.GEN" ) -> SCS
rename(SCS, "familly" = "SPEC.GR2" ) -> SCS

# Retirer les observations contenant l'espèce : "Apis mellifera"
SCS <- filter(SCS, sp != "Apis mellifera" )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus (Bombus)  sp."] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$genus[SCS$genus == "Chalicodoma"] <- "Megachile"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$Site[SCS$Site == "Les Gourmandes de la Procession"] <- "Gourmandes"

# Réécriture des noms de familles
SCS$familly[SCS$familly == "ANDRENIDAE"] <- "Andrenidae"
SCS$familly[SCS$familly == "APIDAE"] <- "Apidae"
SCS$familly[SCS$familly == "COLLETIDAE"] <- "Colletidae"
SCS$familly[SCS$familly == "HALICTIDAE"] <- "Halictidae"
SCS$familly[SCS$familly == "MEGACHILIDAE"] <- "Megachilidae"
SCS$familly[SCS$familly == "MELITTIDAE"] <- "Melittidae"
```

```{r}
SCS %>%
  group_by(sp, Site, genus, familly, Nest_area) %>%
  count(sp) -> df
df$N <- df$n
```

Par espèce
```{r}
# Addition des genres avec la zone de nidification (au dessus du sol ou en dessous)
nest_substrat <- aggregate(N ~ sp + Nest_area, data = df, sum)
```


```{r Espèce}
### Abondance 

nest_substrat_ab <-  spread(nest_substrat, key = Nest_area , value = N)
# Ajoute une ligne total
nest_substrat_ab <- janitor::adorn_totals(nest_substrat_ab)
# Ajoute une colonne total
nest_substrat_ab$Total <- rowSums(nest_substrat_ab[, c("Cavities"  , "Snails",  "Stems" , "Variable" ,"Vegetation", "Wood" ,"Soil", "Walls")])


# Pourcentage rich Cavities
pct_ab_cav <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Cavities"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Next to stems
#pct_ab_nex <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Next to stems"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Snails
pct_ab_sna <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Snails"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Stems
pct_ab_ste <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Stems"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], digits = 2)
# Pourcentage rich Variable
pct_ab_var <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Variable"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Vegetation
pct_ab_veg <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Vegetation"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Wood
pct_ab_woo <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Wood"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)
# Pourcentage rich Soil
pct_ab_soi <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Soil"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], digits = 2)
# Pourcentage rich Walls
pct_ab_wal <- round(nest_substrat_ab[nrow(nest_substrat_ab), "Walls"]/nest_substrat_ab[nrow(nest_substrat_ab), "Total"], 2)

nest_substrat_ab[nrow(nest_substrat_ab) + 1,] = c("Pourcentage", pct_ab_cav,pct_ab_sna,pct_ab_soi,pct_ab_ste, pct_ab_var,pct_ab_veg,pct_ab_wal,pct_ab_woo,"")
```

```{r Espèce}
### Richesse 
nest_substrat_rich <- nest_substrat
# Changer tous les chiffres d'abondances par 1
nest_substrat_rich$N[nest_substrat_rich$N > 0] <- 1  
# Tableau avec colonne (Solitaire, clepto, ...)
nest_substrat_rich <-  spread(nest_substrat_rich, key = Nest_area , value = N)
# Ajoute une ligne total
nest_substrat_rich <- janitor::adorn_totals(nest_substrat_rich)
# Ajoute une colonne total
nest_substrat_rich$Total <- rowSums(nest_substrat_rich[, c("Cavities"  , "Snails",  "Stems" , "Variable" ,"Vegetation", "Wood" ,"Soil", "Walls")])


# Pourcentage rich Cavities
pct_rich_cav <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Cavities"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Next to stems
#pct_rich_nex <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Next to stems"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Snails
pct_rich_sna <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Snails"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Stems
pct_rich_ste <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Stems"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], digits = 2)
# Pourcentage rich Variable
pct_rich_var <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Variable"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Vegetation
pct_rich_veg <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Vegetation"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Wood
pct_rich_woo <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Wood"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)
# Pourcentage rich Soil
pct_rich_soi <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Soil"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], digits = 2)
# Pourcentage rich Walls
pct_rich_wal <- round(nest_substrat_rich[nrow(nest_substrat_rich), "Walls"]/nest_substrat_rich[nrow(nest_substrat_rich), "Total"], 2)

nest_substrat_rich[nrow(nest_substrat_rich) + 1,] = c("Pourcentage", pct_rich_cav,pct_rich_sna,pct_rich_soi,pct_rich_ste, pct_rich_var,pct_rich_veg,pct_rich_wal,pct_rich_woo,"")
```


```{r}
my_df <- list(nest_substrat_ab,nest_substrat_rich)

# Exportation tableur Excel
write_xlsx(my_df, "D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/Output/nest_substrat.xlsx")
```