---
title: "tableau_abondance_par_site"
author: "Jordan"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library("readxl") 
library("writexl")
library(dplyr)
library(vegan) # specpool () estimateR() poolaccum() estaccumR()
library(ggplot2)
library(tidyr)
library(stringr)
#library(fossil)
library(forcats) # fct_collapse
```

Importation des données.
```{r Import}
# Import
# Tour PC
#setwd("D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW")
# Laptop
setwd("C:/Users/Jordan/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/RAW")

SpecCondStat <- read_excel("SpecCondStat.xls")

```

```{r Nettoyage}
# Nom plus compact
SCS <- SpecCondStat

# Retirer le site de Condorcet
SCS <- filter(SCS, TOPO != "Condorcet" )

# Renommer plus simplement
rename(SCS, "sp" = "SPEC.TAXPRIO" ) -> SCS
rename(SCS, "sites" = "TOPO" ) -> SCS

# Retirer les observations contenant l'espèce : "XXX"
# SCS <- filter(SCS, SPEC.TAXPRIO != "Bombus (Bombus)  sp." )

# Remplacement des noms d'espèces désuets
SCS$sp[SCS$sp == "Bombus lucorum"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Bombus terrestris"] <- "Terrestribombus  sp."
SCS$sp[SCS$sp == "Chalicodoma ericetorum"] <- "Megachile ericetorum"
SCS$sp[SCS$sp == "Halictus tumulorum"] <- "Seladonia tumulorum"

# Remplacement du noms de sites
SCS$sites[SCS$sites == "Les Gourmandes de la Procession"] <- "Gourmandes de la Procession"
```


```{r }
# Preparation des données 
data_bee_sp <- select(SCS, sp, N, sites)
data_bee_sp <- as.data.frame(data_bee_sp)
data_bee_sp <- aggregate(N ~ sp + sites, data = data_bee_sp, sum)
data_bee_sp <- xtabs(N ~ sites + sp, data_bee_sp)
data_bee_sp <- type.convert(data_bee_sp)
```

```{r}

## Comparer le nombre de specimens observé dans data_bee_sp
# Rownames to column
total <- tibble::rownames_to_column(as.data.frame(data_bee_sp), "Sites")
# Ajoute une ligne total
total <-  janitor::adorn_totals(total)
# Ajoute une colonne total
total$Total <- rowSums(total[, 2:ncol(total)])
# Valeur total des specimens capturés (coordonnée de la dernière cellule [ligne,colonne])
total[nrow(total),ncol(total)]
# Sp observé total par site
# Garde toutes les lignes et prend la colonne 1 et la dernière (Total) :
total <- total[,c(1,ncol(total))]
# Ordonner par abondance
total <- total[order(total$Total),]
# Renommer les colonnes pour l'Excel
colnames(total) <- c("Sites", "abon")

# Attribuer le type de site
# Liste des Potagers
Potagers <- c("Abbaye St-Denis", "Rue de l'Egalite", "Chasse Cambier", "Mel Legumes", "Gourmandes de la Procession", "Jean d'Avesnes", "Parc du bois de Mons", "Jardin Suspendu", "Ecole de l'Esperance", "Fond du petit marais")
# Liste des Parcs
Parcs <- c("Village des abeilles", "Siege social", "Parc du Beffroi", "Stievenart", "Parc Bonaert")

# Créer une colonne Type en fonction des sites
total$Type <- fct_collapse(
    total$Sites,
    "Potager" = Potagers,
    "Parc" = Parcs,
    NULL = "Total" # réécris total si non
)

# Changement de nom
abondance <- total

abondance
```

```{r}

## Comparer le nombre d'espèces observées dans data_bee_sp


# Rownames to column
total <- tibble::rownames_to_column(as.data.frame(data_bee_sp), "Sites")

# Pas se faire chier, il suffit de remplacer tous les chiffre par 1
total <-  mutate_if(total, is.numeric, ~1 * (. > 0)) 

# Ajoute une ligne total
total <-  janitor::adorn_totals(total)
# Ajoute une colonne total
total$Total <- rowSums(total[, 2:ncol(total)])
# Valeur total des specimens capturés (coordonnée de la dernière cellule [ligne,colonne])
total[nrow(total),ncol(total)]
# Sp observé total par site
# Garde toutes les lignes et prend la colonne 1 et la dernière (Total) :
total <- total[,c(1,ncol(total))]
# Ordonner par abondance
total <- total[order(total$Total),]
# Renommer les colonnes pour l'Excel
colnames(total) <- c("Sites", "rich")

# Attribuer le type de site
# Liste des Potagers
Potagers <- c("Abbaye St-Denis", "Rue de l'Egalite", "Chasse Cambier", "Mel Legumes", "Gourmandes de la Procession", "Jean d'Avesnes", "Parc du bois de Mons", "Jardin Suspendu", "Ecole de l'Esperance", "Fond du petit marais")
# Liste des Parcs
Parcs <- c("Village des abeilles", "Siege social", "Parc du Beffroi", "Stievenart", "Parc Bonaert")


# Créer une colonne Type en fonction des sites
total$Type <- fct_collapse(
    total$Sites,
    "Potager" = Potagers,
    "Parc" = Parcs,
    NULL = "Total" # réécris total si non
)

# Changement de nom
richesse <- total

richesse
```

```{r}
# FUUUUUUSIIIIOOON ! AHhhh !!!
resume_total <- dplyr::left_join(abondance, richesse, by = "Sites")
# Selection des colonnes
resume_total <- select(resume_total, Sites, abon, rich, Type.y)
# Retirer le total d'espèces (incorrecte d'additionner)
resume_total[nrow(resume_total), 3] <- NA
# Renommer proprement
rename(resume_total, "Type" = "Type.y" ) -> resume_total



out$AsyEst -> df
df <- select(df, Site, Diversity , Observed)
spread(out1, Diversity, Observed ) -> df
df$`Shannon diversity` <- round(df$`Shannon diversity`,0)
df$`Species richness` <- round(df$`Species richness`, 0)
df$`Simpson diversity` <- round(df$`Simpson diversity`, 0)


rename(df, "N0" = "Species richness" ) -> df
rename(df, "N1" = "Shannon diversity" ) -> df
rename(df, "N2" = "Simpson diversity" ) -> df
rename(df, "Sites" = "Site" ) -> df



resume_total <- dplyr::left_join(resume_total, df, by = "Sites")

resume_total <- select(resume_total, Sites, abon, N0, N1, N2, Type)

tableau <- arrange(resume_total,  N0)
```

```{r}
#out <- iNEXT(as.data.frame(t(data_bee_sp)), q = c(0,1,2), datatype ="abundance", size=NULL, endpoint=NULL, knots=40, se=TRUE, conf=0.95, nboot=50) 
```

```{r}

# 
# 
# # Matrice Hill
# DataInfotabee <-type.convert(out$DataInfo)
# 
# iNextEsttab <-type.convert(out$iNextEst)
# AsyEsttab <-type.convert(out$AsyEst)
# 
# # Explication colonne estimateD() http://cran.nexr.com/web/packages/iNextPD/vignettes/Introduction.html
# # the diversity estimate of order q (qPD), the 95% lower and upper confidence limits of diversity (qD.95.LCL, qD.95.UCL), and the sample coverage estimate (SC) along with the 95% lower and upper confidence limits of sample coverage (SC.95.LCL, SC.95.UCL). These sample coverage estimates with conf% confidence intervals are used for plotting the sample completeness curve and coverage-based R/E curves.
# 
# hill <- estimateD(t(data_bee_sp), base="coverage") # par défaut conf = 0.95
# hillmatrix0= hill[hill[,"order"]==0,]
# hillmatrix1= hill[hill[,"order"]==1,]
# hillmatrix2= hill[hill[,"order"]==2,]
# hillmatrix = hillmatrix0[,c(1,2,4)]
# hillmatrix$SC0 = out$DataInfo$SC
# hillmatrix[,c("N0","N0rU","N0rL")]=hillmatrix0[,c("qD","qD.UCL","qD.LCL")] # q = ordre, D = diversité, UCL = UpperConfidenceLimits, LCL = LowerCL
# hillmatrix[,c("N1","N1rU","N1rL")]=hillmatrix1[,c("qD","qD.UCL","qD.LCL")] # Je retire NOr => N0, idem N1 et N2
# hillmatrix[,c("N2","N2rU","N2rL")]=hillmatrix2[,c("qD","qD.UCL","qD.LCL")]
# rownames(hillmatrix)= rownames(data_bee_sp)
# 
# # Rownames to column
# hillmatrix <- tibble::rownames_to_column(as.data.frame(hillmatrix), "Sites")
# hillmatrix$N0 <- round(hillmatrix$N0)
# hillmatrix$N1 <- round(hillmatrix$N1)
# hillmatrix$N2 <- round(hillmatrix$N2)
# hillmatrix <- select(hillmatrix, Sites,N0,N1,N2)
```

```{r}
# FUUUUUUSIIIIOOON ! AHhhh !!! SSJ4
# resume_total <- dplyr::left_join(resume_total,hillmatrix, by = "Sites")
# 
# # Selection des colonnes
# resume_total <- select(resume_total, Sites, abon, N0, N1, N2, Type)
# rename(resume_total, "Nombre d'individus observées" = "abon" ) -> resume_total
# #rename(resume_total, "Nombre d'espèces observées" = "richesse" ) -> resume_total
```


```{r}
# Exportation tableur Excel
write_xlsx(tableau, "D:/OneDrive - UMONS/UMONS/MA2/MEMOIRE/Statistique/R/STAT-MEMOIRE/Output/tableau_HILL.xlsx")
```










